volumes:
  postgres-data:
    driver: local

services:
  ecomie-web:
    container_name: ecomie-web
    image: dbryzz/ecomie-web:latest
    env_file:
      - ./.env
    ports:
      - "${WEB_PORT:-80}:80"
    depends_on:
      ecomie-api:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${WEB_PORT:-80}" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ecomie-network
    restart: on-failure:3

  ecomie-api:
    container_name: ecomie-api
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - .:/build
#      - /build/target
    ports:
      - "${HTTP_PORT}:${PORT}"
#    stdin_open: true
#    tty: true
    depends_on:
      ecomie-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${PORT:-8081}${API_BASE_URL:-/api/v1}/health" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ecomie-network
    restart: on-failure:3

  ecomie-db:
    container_name: ecomie-db
    image: postgres:18-alpine
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATASOURCE_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      - ecomie-network
    restart: always

networks:
  ecomie-network:
    driver: bridge
